services:
  - type: web
    name: jlm-elearning-backend
    runtime: node
    plan: free
# render file
    buildCommand: cd backend && npm install --include=dev && npx prisma generate && npm run build
    startCommand: cd backend && node dist/main.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_EMAIL_VERIFICATION
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false

    autoDeploy: true
    healthCheckPath: /api/health
