### Register Admin
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123",
  "firstName": "Admin",
  "lastName": "User",
  "role": "ADMIN"
}

### Register Instructor
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "instructor@example.com",
  "password": "password123",
  "firstName": "John",
  "lastName": "Doe",
  "role": "INSTRUCTOR"
}

### Register Student
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "student@example.com",
  "password": "password123",
  "firstName": "Jane",
  "lastName": "Smith"
}
